{% set name = "zchunk" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zchunk/zchunk/archive/{{ version }}.tar.gz
  sha256: 7068fbf30b613b3e4ac80ec291ebdbc08c70c7ce81af1f689d9eaf32bac3a027

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - pkg-config  # [osx or win]
    - ninja
  host:
    - libcurl
    - openssl
    - zstd
  run:
    - libcurl
    - openssl
    - zstd

test:
  commands:
    - test -f ${PREFIX}/lib/libzck${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/bin/zck  # [unix]
    - test -f ${PREFIX}/include/zck.h  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/zck.pc  # [unix]

about:
  home: https://github.com/zchunk/zchunk
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A file format designed for highly efficient deltas while maintaining good compression
  description: |
    zchunk is a compressed file format that splits the file into independent
    chunks. This allows you to only download changed chunks when downloading a
    new version of the file, and also makes zchunk files efficient over rsync.

    zchunk files are protected with strong checksums to verify that the file
    you downloaded is, in fact, the file you wanted.

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - SylvainCorlay
